apiVersion: v2
name: subcontracts-service
description: Lante Subcontractor Engagement & Prequalification Service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "18.5.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
