using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinanceService.Infrastructure.Migrations
{
    /// <inheritdoc />
    /// <remarks>
    /// #332 -- finance has no delete path anywhere in the service: zero writes to IsDeleted across
    /// all 39 tables that carried it (confirmed by grep, not assumed), and 21 of them additionally
    /// carried a HasQueryFilter checking a column that could never be anything but false -- the same
    /// shape as Role.IsSystem (#272) and ForexRevaluationLog (#226). No data loss: every row's value
    /// was always false, so dropping the column removes zero information.
    ///
    /// Generated by `dotnet ef migrations add` directly this time, not hand-authored -- #337/#348
    /// already fully reconciled finance's timestamp columns, so there is no drift left for the CLI
    /// to bundle in. Reviewed anyway: exactly 39 DropColumn operations, nothing else.
    /// </remarks>
    public partial class DropIsDeletedColumn : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "VatReturns");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "TaxCategories");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Suppliers");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "SupplierInvoices");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "SupplierInvoiceLines");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "StatutoryRemittances");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "RevenueTargets");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PersonalAdvances");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PeriodCloseLogs");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PeriodCloseChecklistItems");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PaymentVouchers");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Payments");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PaymentApprovalTiers");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PaymentApprovalLogs");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "PaymentAllocations");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "JournalLines");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "JournalEntries");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Invoices");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "InvoiceLines");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "ImprestRetirementLines");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "ImprestRequests");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "GeneralLedgerEntries");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "ForexRevaluationLogs");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "FixedAssets");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "FiscalYears");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "FinanceAuditLogs");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "EtimsSubmissions");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "DepreciationEntries");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Customers");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Currencies");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "CostCenters");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "ChartOfAccounts");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "Budgets");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "BankStatementLines");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "BankReconciliations");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "AssetDisposals");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "AssetCategories");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "AccountTypes");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                table: "AccountingPeriods");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "VatReturns",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "TaxCategories",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Suppliers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "SupplierInvoices",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "SupplierInvoiceLines",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "StatutoryRemittances",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "RevenueTargets",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PersonalAdvances",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PeriodCloseLogs",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PeriodCloseChecklistItems",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PaymentVouchers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Payments",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PaymentApprovalTiers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PaymentApprovalLogs",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "PaymentAllocations",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "JournalLines",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "JournalEntries",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Invoices",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "InvoiceLines",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "ImprestRetirementLines",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "ImprestRequests",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "GeneralLedgerEntries",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "ForexRevaluationLogs",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "FixedAssets",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "FiscalYears",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "FinanceAuditLogs",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "EtimsSubmissions",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "DepreciationEntries",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Customers",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Currencies",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "CostCenters",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "ChartOfAccounts",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "Budgets",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "BankStatementLines",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "BankReconciliations",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "AssetDisposals",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "AssetCategories",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "AccountTypes",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                table: "AccountingPeriods",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }
    }
}
