{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "store-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "store-service.labels" . | nindent 4 }}
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      {{- include "store-service.selectorLabels" . | nindent 6 }}
{{- end }}
