{{- if .Values.ghcrSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.ghcrSecret.dockerconfigjson }}
{{- end }}
