using Asp.Versioning;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ComplianceService.Core.DTOs.Common;
using ComplianceService.Core.DTOs.Statutory;
using ComplianceService.Core.Entities;
using ComplianceService.Core.Enums;
using ComplianceService.Core.Interfaces.Repositories;
using ComplianceService.Core.Interfaces.Services;

namespace ComplianceService.Api.Controllers;

// Dated instances of a StatutoryObligation. Recurring (Monthly/Quarterly) deadlines are
// auto-generated by StatutoryCalendarBackgroundService; Annually obligations (corporate/
// instalment tax) get their deadlines created here manually since the exact date varies.
[ApiController]
[ApiVersion("1.0")]
[Route("api/v{version:apiVersion}/statutory-deadlines")]
public class StatutoryDeadlinesController(
    IComplianceCrudService<StatutoryDeadline> deadlines,
    IComplianceCrudService<StatutoryObligation> obligations,
    IStatutoryDeadlineRepository deadlinesRepository,
    IStatutoryDashboardService dashboard) : ControllerBase
{
    [HttpGet]
    [Authorize(Policy = "statutory.read")]
    public async Task<ActionResult<ApiResponse<PaginatedResult<StatutoryDeadlineReadDto>>>> GetAll([FromQuery] StatutoryDeadlineFilterParameters parameters)
    {
        var paged = await deadlinesRepository.GetPagedAsync(parameters);
        var names = (await obligations.GetAllAsync()).ToDictionary(o => o.Id, o => (o.Name, o.Authority));
        var result = new PaginatedResult<StatutoryDeadlineReadDto>
        {
            Items = paged.Items.Select(d => ToReadDto(d, names)).ToList(),
            TotalCount = paged.TotalCount,
            Page = paged.Page,
            PageSize = paged.PageSize
        };
        return Ok(ApiResponse<PaginatedResult<StatutoryDeadlineReadDto>>.Ok(result));
    }

    [HttpPost]
    [Authorize(Policy = "statutory.write")]
    public async Task<ActionResult<ApiResponse<StatutoryDeadlineReadDto>>> CreateManual([FromQuery] string obligationId, [FromQuery] DateTime dueDate)
    {
        var obligation = await obligations.GetByIdAsync(obligationId);
        if (obligation == null) return NotFound(ApiResponse<StatutoryDeadlineReadDto>.Fail("Obligation not found.", 404));

        var deadline = new StatutoryDeadline
        {
            ObligationId = obligationId,
            DueDate = dueDate,
            OwnerUserId = obligation.OwnerUserId,
            OwnerName = obligation.OwnerName,
        };
        await deadlines.CreateAsync(deadline);
        var names = new Dictionary<string, (string, string)> { [obligation.Id] = (obligation.Name, obligation.Authority) };
        return Ok(ApiResponse<StatutoryDeadlineReadDto>.Ok(ToReadDto(deadline, names), "Deadline scheduled."));
    }

    [HttpPatch("{id}/file")]
    [Authorize(Policy = "statutory.write")]
    public async Task<ActionResult<ApiResponse<StatutoryDeadlineReadDto>>> MarkFiled(string id, [FromBody] MarkDeadlineFiledDto dto)
    {
        var d = await deadlines.GetByIdAsync(id);
        if (d == null) return NotFound(ApiResponse<StatutoryDeadlineReadDto>.Fail("Deadline not found.", 404));

        d.Status = StatutoryDeadlineStatus.Filed;
        d.FiledOn = dto.FiledOn ?? DateTime.UtcNow;
        await deadlines.UpdateAsync(d);
        var names = (await obligations.GetAllAsync()).ToDictionary(o => o.Id, o => (o.Name, o.Authority));
        return Ok(ApiResponse<StatutoryDeadlineReadDto>.Ok(ToReadDto(d, names), "Deadline marked as filed."));
    }

    private StatutoryDeadlineReadDto ToReadDto(StatutoryDeadline d, Dictionary<string, (string Name, string Authority)> names)
    {
        names.TryGetValue(d.ObligationId, out var info);
        return new StatutoryDeadlineReadDto
        {
            Id = d.Id,
            ObligationId = d.ObligationId,
            ObligationName = info.Name,
            Authority = info.Authority,
            DueDate = d.DueDate,
            Status = d.Status,
            FiledOn = d.FiledOn,
            OwnerUserId = d.OwnerUserId,
            OwnerName = d.OwnerName,
            Rag = dashboard.ComputeRag(d.DueDate),
        };
    }
}
