apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fleet-service.fullname" . }}-uploads
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fleet-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
