// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OperationsService.Infrastructure.Data;

#nullable disable

namespace OperationsService.Infrastructure.Migrations
{
    [DbContext(typeof(OperationsDbContext))]
    [Migration("20260513201155_AddPreDeploymentChecklist")]
    partial class AddPreDeploymentChecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OperationsService.Core.Entities.AdvanceReturnForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountReturned")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerComments")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAccountedFor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AdvanceReturnForms");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AdvanceReturnLineItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AdvanceReturnFormId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdvanceReturnFormId");

                    b.ToTable("AdvanceReturnLineItems");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AssignedTechnician", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("AssignedTechnicians");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Assignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LinkedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LinkedBy")
                        .HasColumnType("text");

                    b.Property<string>("LinkedMilestoneId")
                        .HasColumnType("text");

                    b.Property<string>("LinkedProjectId")
                        .HasColumnType("text");

                    b.Property<string>("LinkedProjectTaskId")
                        .HasColumnType("text");

                    b.Property<string>("LinkedTicketId")
                        .HasColumnType("text");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("text");

                    b.Property<double?>("LocationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("LocationName")
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NatureOfVisit")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceRequestDataJson")
                        .HasColumnType("text");

                    b.Property<string>("ServiceRequestId")
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.BudgetLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("BudgetLines");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.CheckIn", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("CheckIns");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Claim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisbursedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<string>("ManagerComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManagerReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ManagerReviewedBy")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupportingDocuments")
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.CostEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignmentId")
                        .HasColumnType("text");

                    b.Property<string>("BudgetLineId")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MilestoneId")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BudgetLineId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("ProjectId");

                    b.ToTable("CostEntries");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.DailySummary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Challenges")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ExpensesIncurred")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NextDayPlan")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.FieldVehicle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentOdometer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InsuranceExpiry")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("LastServiceOdometer")
                        .HasColumnType("numeric");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextServiceDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FieldVehicles");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.FuelLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("AmountLitres")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostKes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DispatchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DispatchId");

                    b.ToTable("FuelLogs");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.LabWorkOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BenchChecklistJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BenchCompletedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BenchNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BenchStartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BenchSubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("BenchTechnicianId")
                        .HasColumnType("text");

                    b.Property<string>("BenchTechnicianName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CertificateIssuedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CertificateNotes")
                        .HasColumnType("text");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DispatchMethod")
                        .HasColumnType("text");

                    b.Property<string>("DispatchNotes")
                        .HasColumnType("text");

                    b.Property<string>("IntakeConditionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IntakeDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IntakeTechnicianId")
                        .HasColumnType("text");

                    b.Property<string>("IntakeTechnicianName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("JobNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("text");

                    b.Property<string>("ServiceRequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TmApprovalNotes")
                        .HasColumnType("text");

                    b.Property<string>("TmRejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TmReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TmReviewedById")
                        .HasColumnType("text");

                    b.Property<string>("TmReviewedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("LabWorkOrders");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Milestone", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlannedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PerDiemReturnForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<decimal>("FaresOrCarExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Incidentals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LineItemsJson")
                        .HasColumnType("text");

                    b.Property<string>("ManagerComments")
                        .HasColumnType("text");

                    b.Property<decimal>("Meals")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Medical")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Mileage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("PerDiemReturnForms");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PerformanceMetrics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AlertLevel")
                        .HasColumnType("integer");

                    b.Property<double>("AmberThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("ApprovedRequisitions")
                        .HasColumnType("integer");

                    b.Property<double>("AverageCompletionMinutes")
                        .HasColumnType("double precision");

                    b.Property<int>("CompletedAssignments")
                        .HasColumnType("integer");

                    b.Property<double>("CompletionRate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DelayedAssignments")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("OnTimeRate")
                        .HasColumnType("double precision");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("RedThreshold")
                        .HasColumnType("double precision");

                    b.Property<double>("ReportApprovalRate")
                        .HasColumnType("double precision");

                    b.Property<int>("ReportsApproved")
                        .HasColumnType("integer");

                    b.Property<int>("ReportsRejected")
                        .HasColumnType("integer");

                    b.Property<int>("ReportsSubmitted")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAssignments")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRequisitionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalRequisitions")
                        .HasColumnType("integer");

                    b.Property<double>("TotalWorkingHours")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PettyCashAdvanceForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("text");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DisbursedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisbursedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PreparedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("PettyCashForms");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Photo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("StorageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PreDeploymentChecklist", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SubmittedById")
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("PreDeploymentChecklists");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClientName")
                        .HasColumnType("text");

                    b.Property<string>("ClientReference")
                        .HasColumnType("text");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CrmLeadId")
                        .HasColumnType("text");

                    b.Property<string>("DepartmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpectedEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PlannedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProjectManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeSummary")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TenderReference")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectApproval", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectApprovals");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectHistories");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectResources");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkedAssignmentId")
                        .HasColumnType("text");

                    b.Property<string>("MilestoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LinkedAssignmentId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("ProjectTasks", (string)null);
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Refund", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ManagerComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ManagerReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ManagerReviewedBy")
                        .HasColumnType("text");

                    b.Property<int?>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReceivedBy")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Refunds");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Requisition", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CfoComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CfoReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CfoReviewedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemsList")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<string>("LineItemsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RejectedBy")
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TmComments")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TmReviewedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TmReviewedBy")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VoucherNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ServiceReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerComments")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerSignatureData")
                        .HasColumnType("text");

                    b.Property<string>("CustomerSignatureName")
                        .HasColumnType("text");

                    b.Property<int>("DepartmentType")
                        .HasColumnType("integer");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationAddress")
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NatureOfVisit")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("SignatureData")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartDay")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicianSignatureData")
                        .HasColumnType("text");

                    b.Property<string>("TechnicianSignatureName")
                        .HasColumnType("text");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("ServiceReports");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.VehicleDispatch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DepartureOdometer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldVehicleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FuelLevelIn")
                        .HasColumnType("text");

                    b.Property<string>("FuelLevelOut")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("ReturnOdometer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("FieldVehicleId");

                    b.ToTable("VehicleDispatches");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AdvanceReturnForm", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("AdvanceReturnForms")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AdvanceReturnLineItem", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.AdvanceReturnForm", "Form")
                        .WithMany("LineItems")
                        .HasForeignKey("AdvanceReturnFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AssignedTechnician", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("Technicians")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Attachment", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", null)
                        .WithMany("Attachments")
                        .HasForeignKey("AssignmentId");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.BudgetLine", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("BudgetLines")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.CheckIn", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("CheckIns")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Claim", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("Claims")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.CostEntry", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.BudgetLine", "BudgetLine")
                        .WithMany("CostEntries")
                        .HasForeignKey("BudgetLineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OperationsService.Core.Entities.Milestone", "Milestone")
                        .WithMany("CostEntries")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("CostEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetLine");

                    b.Navigation("Milestone");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.DailySummary", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.FuelLog", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.VehicleDispatch", "Dispatch")
                        .WithMany("FuelLogs")
                        .HasForeignKey("DispatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatch");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.LabWorkOrder", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithOne("LabWorkOrder")
                        .HasForeignKey("OperationsService.Core.Entities.LabWorkOrder", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Milestone", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PerDiemReturnForm", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("PerDiemForms")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PettyCashAdvanceForm", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("PettyCashForms")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Photo", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("Photos")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.PreDeploymentChecklist", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectApproval", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("Approvals")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectHistory", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("History")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectResource", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Project", "Project")
                        .WithMany("Resources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ProjectTask", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "LinkedAssignment")
                        .WithMany()
                        .HasForeignKey("LinkedAssignmentId");

                    b.HasOne("OperationsService.Core.Entities.Milestone", "Milestone")
                        .WithMany("Tasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedAssignment");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Refund", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("Refunds")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Requisition", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("Requisitions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.ServiceReport", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("ServiceReports")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.VehicleDispatch", b =>
                {
                    b.HasOne("OperationsService.Core.Entities.Assignment", "Assignment")
                        .WithMany("VehicleDispatches")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OperationsService.Core.Entities.FieldVehicle", "FieldVehicle")
                        .WithMany("Dispatches")
                        .HasForeignKey("FieldVehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("FieldVehicle");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.AdvanceReturnForm", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Assignment", b =>
                {
                    b.Navigation("AdvanceReturnForms");

                    b.Navigation("Attachments");

                    b.Navigation("CheckIns");

                    b.Navigation("Claims");

                    b.Navigation("LabWorkOrder");

                    b.Navigation("PerDiemForms");

                    b.Navigation("PettyCashForms");

                    b.Navigation("Photos");

                    b.Navigation("Refunds");

                    b.Navigation("Requisitions");

                    b.Navigation("ServiceReports");

                    b.Navigation("Technicians");

                    b.Navigation("VehicleDispatches");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.BudgetLine", b =>
                {
                    b.Navigation("CostEntries");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.FieldVehicle", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Milestone", b =>
                {
                    b.Navigation("CostEntries");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.Project", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("BudgetLines");

                    b.Navigation("CostEntries");

                    b.Navigation("History");

                    b.Navigation("Milestones");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("OperationsService.Core.Entities.VehicleDispatch", b =>
                {
                    b.Navigation("FuelLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
