{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crm-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crm-service.labels" . | nindent 4 }}
{{- end }}
