replicaCount: 1

image:
  repository: ghcr.io/lante-africa/lante-erp/user-service
  pullPolicy: Always
  tag: ""

imagePullSecrets:
  - name: ghcr-credentials

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "2Gi"
    cpu: "1000m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

storage:
  publicBaseUrl: "https://kmk.support.qalibrated.co.ke"
  size: 2Gi
  storageClass: ""

postgresql:
  enabled: true
  auth:
    existingSecret: "lante-erp-secrets"
  primary:
    persistence:
      size: 20Gi
