namespace HrService.Core.Enums;

/// <summary>HR-004 — employment status lifecycle. A new hire starts <see cref="OnProbation"/> (H2 confirms
/// them to <see cref="Active"/> after the 3/6-month reviews); separation (H10) sets Resigned/Terminated.</summary>
public enum EmploymentStatus
{
    OnProbation,
    Active,
    OnLeave,
    Suspended,
    Resigned,
    Terminated,
}

/// <summary>Contract basis. FixedTerm/Contract carry an end date and drive the H2 contract-renewal alerts
/// (HR-006: 30-day and 7-day warnings before expiry).</summary>
public enum EmploymentType
{
    Permanent,
    FixedTerm,
    Contract,
    Intern,
    Casual,
}

/// <summary>HR-002 — document vault kinds. A signed contract and an ID copy are the two the design notes
/// require before onboarding counts as complete.</summary>
public enum EmployeeDocumentType
{
    SignedContract,
    IdCopy,
    AcademicCertificate,
    ProfessionalCertificate,
    MedicalRecord,
    KraPinCertificate,
    NssfCard,
    ShaCard,
    PassportPhoto,
    Other,
    // H3 (P5 step 5.3) — leave-supporting documents. Appended, never reordered: the stored values are ints.
    MedicalCertificate,
    AntenatalBooking,
    BirthCertificate,
    InstitutionLetter,
}

/// <summary>HR audit trail (ARCH-007). Appended per phase.</summary>
public enum HrAuditAction
{
    // H1 — employee master, documents, org chart
    EmployeeCreated,
    EmployeeUpdated,
    UserAccountCreated,
    UserAccountFailed,
    DocumentUploaded,
    DocumentVerified,
    CertificationRegistered,
    OnboardingCompleted,
    PositionCreated,
    OrgChartRebuilt,
    ReportingLineChanged,
    // H2 — probation tracking & contract renewal
    ProbationReviewRaised,
    ProbationConfirmed,
    ProbationExtended,
    ProbationTerminationRecommended,
    ContractAlertRaised,
    ContractRenewed,
    ContractConvertedToPermanent,
    ContractExpired,
    // H3 — leave configuration, applications, approvals, carry-forward
    LeaveTypeConfigured,
    LeaveEntitlementAssigned,
    LeaveEntitlementAdjusted,
    LeaveRequested,
    LeaveApprovalStepRecorded,
    LeaveApproved,
    LeaveRejected,
    LeaveCancelled,
    LeaveDocumentAttached,
    LeaveCarriedForward,
    LeaveForfeited,
    LeaveCarryForwardExpired,
    // H4 — attendance, absence and the monthly/annual reporting
    AttendanceClockedIn,
    AttendanceClockedOut,
    LateArrivalFlagged,
    AbsenceRecorded,
    AbsenceExcused,
    AbsencePatternFlagged,
    AttendanceSettingsChanged,
    PublicHolidayConfigured,
    AttendanceReportGenerated,
    AttendanceScorecardUpdated,
    // H5 — salary structures, pay assignments, statutory rates, deductions
    JobGradeConfigured,
    SalaryStructureConfigured,
    SalaryComponentConfigured,
    GlAccountMapped,
    PayrollPeriodsGenerated,
    SalaryProposed,
    SalaryApproved,
    SalaryRejected,
    SalarySuperseded,
    PayeBandConfigured,
    StatutoryRateConfigured,
    StatutoryRatesConfirmed,
    DeductionTypeConfigured,
    DeductionApplied,
    DeductionStopped,
    // H6 — overtime pre-approval, payroll runs, payslips and the finance journal
    OvertimeRequested,
    OvertimeApproved,
    OvertimeRejected,
    PayrollRunCreated,
    PayrollRunComputed,
    PayrollRunApproved,
    PayrollRunCancelled,
    PayrollJournalPosted,
    PayrollJournalFailed,
    BankFileGenerated,
    BankFileConfirmed,
    // H7 — learning & development, training hours, mandatory compliance, knowledge sharing, budgets
    LdpSubmitted,
    LdpApproved,
    LdpRejected,
    LdpReminderSent,
    LdpEscalated,
    TrainingLogged,
    TrainingObjectiveCompleted,
    MandatoryRequirementConfigured,
    MandatoryTrainingBreached,
    ZeroTrainingHoursFlagged,
    KnowledgeSessionLogged,
    KnowledgeSharingShortfall,
    LdBudgetConfigured,
    LdBudgetThresholdReached,
    // H8 — salary increments
    SalaryIncrementProposed,
    SalaryIncrementApproved,
    SalaryIncrementRejected,
    SalaryIncrementWithdrawn,
    // H9 — KPI scorecards, appraisals, 360 feedback, improvement plans
    KpiScorecardConfigured,
    KpiTargetsAssigned,
    AppraisalCycleOpened,
    AppraisalSelfSubmitted,
    AppraisalReviewed,
    AppraisalSignedOff,
    AppraisalRecorded,
    Feedback360Requested,
    Feedback360Submitted,
    PipRaised,
    PipClosed,
    // H10 — discipline, warnings, grievances, separation
    DisciplinaryCaseOpened,
    ShowCauseIssued,
    DisciplinaryResponseRecorded,
    DisciplinaryHearingHeld,
    DisciplinaryOutcomeRecorded,
    DisciplinaryAppealRecorded,
    DisciplinaryCaseClosed,
    WarningIssued,
    WarningAcknowledged,
    WarningExpired,
    WarningEscalation,
    GrievanceSubmitted,
    GrievanceAcknowledged,
    GrievanceAssigned,
    GrievanceResolved,
    GrievanceEscalated,
    SeparationInitiated,
    SeparationApproved,
    SeparationPaid,
    SeparationCancelled,
    // H11 — commission
    CommissionBandConfigured,
    CommissionPlanSubmitted,
    CommissionPlanApproved,
    CommissionStatementComputed,
    CommissionStatementApproved,
    CommissionStatementPaid,
    CommissionDisputeRaised,
    CommissionDisputeResolved,
    CommissionRedFlag,
    // H12 — recruitment: requisition, vacancy, applicant, interview, offer, hire
    RequisitionRaised,
    RequisitionSubmitted,
    RequisitionApproved,
    RequisitionRejected,
    RequisitionCancelled,
    VacancyPosted,
    VacancyClosed,
    VacancyFilled,
    VacancyCancelled,
    ApplicationReceived,
    ApplicantShortlisted,
    ApplicantRejected,
    ApplicantWithdrawn,
    InterviewScheduled,
    InterviewScored,
    InterviewCancelled,
    OfferPrepared,
    OfferSubmitted,
    OfferApproved,
    OfferRejected,
    OfferIssued,
    OfferAccepted,
    OfferDeclined,
    OfferWithdrawn,
    OfferLapsed,
    CandidateHired,
}
